### ISSUE TITLE
TerraformFmt breaks up block comments

### ISSUE THREAD

**Issue by ahl** [hashivim/vim-terraform#16] opened 2016-12-17 01:15 UTC
It turns this:
```
# One
# Long
# Comment
```

Into this:
```
# One

# Long

# Comment
```

**Comment by ashb** [comment] 2017-06-29 08:28
@ahl I can't reproduce this from the sample given. Does this still happen? At least in the current version of this plugin the formatting is handled by running through `terraform fmt` so if this does still happen it's a bug in terraform, not this plugin.

**Comment by ahl** [comment] 2017-07-10 18:58
seems to be fixed; thanks!

(also nice profile icon! my friend, Eileen, started Ritual)

**Comment by pgporada** [comment] 2017-07-10 19:08
@ahl I'm going to close this out then. Best of luck!

**Closed by pgporada** 2017-07-10 19:08 UTC
Labels: bug, help wanted
